server:
  port: 9191
  context-path: /

endpoints:
  shutdown:
    enabled: true #启用shutdown
    #禁用密码验证
    #sensitive: false
    sensitive: true
    path: /custompath #指定shutdown endpoint的路径

security:
  user:
    name: admin #验证用户名
    password: secret #验证密码

management:
  security:
    role: SUPERUSER #角色
  context-path: /manage #也可以统一指定所有endpoints的路径`
  
logging.config: classpath:log4j2.xml

mybatis: 
  mapperLocations: classpath:com/test/mapper/*.xml
  typeAliasesPackage: tk.mapper.model 

spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.0.105:3306/boot_sql
    username: clwtest
    password: clwtest
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20